name: Deploy botlist.json to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'botlist.json'
      - 'botlist.txt'
      - '.github/workflows/publish.yaml

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify botlist.json exists
        run: |
          if [ ! -f botlist.json ]; then
            exit 1
          fi

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
